version: "3.9"
services:
  postgres-sandbox:
    image: postgres:14 # Pull the docker image
    ports:
      - '5432:5432' # Publish container's 5432 port to the host's 5432 port
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    environment: # Set environment credentials
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password